import React from "react";
import { Link } from "react-router-dom";
import { ROUTES } from "../../router/routes";

const Terms = () => {
  return (
    <div className="px-5 py-3 md:py-7">
      <h3 className="text-center text-[30px] font-semibold">
        Terms and Condition
      </h3>
      <div className="leading-7 sm:leading-10  md:text-[20px]">
        <p>
          These terms of use (<strong>&ldquo;Terms&rdquo;</strong>) mandate the
          terms on which the content creators (
          <strong>
            &ldquo;You&rdquo; or &ldquo;Your&rdquo; or &ldquo;Yourself&rdquo; or
            &ldquo;User&rdquo;
          </strong>
          ) access and register on the web application &lsquo;CreatorApp&rsquo;
          owned and operated by Stanverse Technologies Private Limited (
          <strong>&ldquo;Company&rdquo;</strong>), having its registered office
          at{" "}
          <strong>
            459 1st floor khata no 357/459 HSR Layout, Bangalore South,
            Bangalore, Karnataka
          </strong>
          , collectively referred to as (
          <strong>&ldquo;the Platform&rdquo;</strong>), for the purpose of
          availing the Services (as defined hereinafter) provided by the
          Company.
        </p>
        <p>
          These Terms are an electronic record in terms of the Indian Contract
          Act, 1872; The Information Technology Act, 2000 and rules made
          thereunder as applicable. The Terms is (i) published in accordance
          with the provisions of Rule 3(1)(a) of the Information Technology
          (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021,
          and amendments from time to time; and (ii) generated by a computer
          system and does not require any physical, electronic, or digital
          signatures.
        </p>
        <p>
          Please read the Terms and Privacy Policy ({" "}
          <Link className="text-sky-textBlue" to={ROUTES.PRIVACY}>
            {" "}
            &ldquo;Privacy Policy&rdquo;{" "}
          </Link>
          ) carefully before using or registering on the Platform or accessing
          any material information through the Platform. By accessing the
          Platform as a User, You accept these Terms and Privacy Policy and
          agree to be legally bound by the same. Further, by furnishing Your
          Personal Information (as defined in the Privacy Policy) (
          <strong>&ldquo;Personal Information&rdquo;</strong>) to the Company or
          giving Your consent to the Company to access Your Personal Information
          for the purpose of rendering the Services (as defined below), You also
          agree that You are interested in availing the Services through the
          Platform in accordance with these Terms.
        </p>
        <p>
          <strong>
            IF YOU DO NOT AGREE TO BE BOUND BY ALL TERMS AND CONDITIONS CAPTURED
            IN THE TERMS, PLEASE DO NOT USE THE PLATFORM OR SERVICES
          </strong>
        </p>
        <h4>1. Applicability</h4>
        <p>
          These Terms shall be applicable to You only if You have created an
          account on the Platform (<strong>&ldquo;Account&rdquo;</strong>) by
          providing such information as may be required as set out further in
          Our Privacy Policy.
        </p>
        <h4>2. Eligibility to Use</h4>
        <ul>
          <li>
            2.1. You shall be eligible to avail Services on the Platform subject
            to registering with Us as a User and holding an Account as detailed
            in Clause 3 below and subject to executing a service agreement with
            the Company (<strong>&ldquo;Service Agreement&rdquo;</strong>).
          </li>
          <li>
            2.2. The Services are not available to minors i.e., persons under
            the age of 18 (eighteen) years or to any Users suspended or removed
            by the Company for any reason whatsoever. By using Platform, You
            affirm that (a) You are at least 18 years of age; or (b) are a
            corporation, duly organized, validly existing and in good standing
            under the laws of the jurisdiction of Your organization, and are
            fully able and competent to enter into the Terms, conditions,
            obligations, affirmations, representations, warranties set forth in
            the Terms and Conditions, and to abide by and comply with the Terms
            stated therein. Registration of User and creation of Account on the
            Platform is available only to persons who can form legally binding
            contracts under Indian Contract Act, 1872.
          </li>
          <li>
            2.3. We maintain the right to provide Services to only those Users
            who are &ndash; (a) competent to enter into legally binding
            contracts, (b) have made the representations as provided above, (c)
            and also qualify under the internal policy(ies) for the same
            determined solely by Us from time to time. We shall have the sole
            right to change, modify, add, or remove, in whole or in part,
            internal policy(ies), in relation to the provision of the Services
            at any time by providing a prior written notice or intimation to the
            Users.
          </li>
          <li>
            2.4. You shall not have more than one active Account on the
            Platform. Additionally, You are prohibited from selling, trading, or
            otherwise transferring Your Account to another party or
            impersonating any other person for the purposing of creating an
            Account with the Platform.
          </li>
          <li>
            2.5. You hereby agree and acknowledge that the Company allows You to
            register on the Platform based on a preliminary examination of the
            information provided by You on the Platform during the creation of
            Your Account. The Company does not and will not undertake any fact
            finding or verification process to evaluate the veracity of the
            information provided by You or on the basis of how the Platform is
            subsequently used by You including but not limited to content shared
            by You through the usage of the Platform.
          </li>
          <li>
            2.6. By accessing the Platform or by accessing the Software or any
            of the Services, it is deemed that the User has read and understood
            and accepted these Terms and has executed the Service Agreement and
            agreed to be bound by it. If You will be using the Services on
            behalf of an organization, You agree to these Terms on behalf of
            that organization and You represent that You have the authority to
            do so.
          </li>
        </ul>
        <h4>3. User Account Registration</h4>
        <ul>
          <li>
            3.1. You may browse certain sections of the Platform without having
            an Account with Us. However, to avail the Services (defined below)
            on the Platform ,You need to create an Account by providing such
            information as may be required by the Company as provided under the
            Privacy Policy. Such details may also include proof of
            identification in a manner prescribed by the Company from time to
            time. You may create Your Account on the Platform by entering the
            one time verification password generated by the Company for this
            purpose which shall be sent to the phone number entered by You on
            the Platform.
          </li>
          <li>
            3.2. You shall ensure and confirm that the Account information and
            all information provided by You is complete, accurate and
            up-to-date. If there is any change in the Account information, or if
            any information is found to be incomplete or incorrect, You shall
            promptly update Your Account information on the Platform or request
            the Company for an information revision or update. If You provide
            any information that is untrue, inaccurate, unauthorized, not
            current, or incomplete (or becomes untrue, inaccurate, not current,
            or incomplete), or if the Company has reasonable grounds to suspect
            that such information is untrue, inaccurate, not current, or
            incomplete, the Company has the right to refuse any and all the
            Services to You.
          </li>
          <li>
            3.3. You are responsible for maintaining the confidentiality of the
            Account information, safeguarding the password or credentials that
            You use to access the Service and for any activities or actions
            under Your Account. You are encouraged to use &ldquo;strong&rdquo;
            passwords (passwords that use a combination of upper and lower-case
            letters, numbers and symbols) with Your Account and with other
            accounts that You may connect to Your Account (such as Your Accounts
            with other social media platforms).
          </li>
          <li>
            3.4. You agree to (a) immediately notify the Company of any
            unauthorized use of Your Account information or any other breach of
            security, and (b) ensure that You exit from Your Account at the end
            of each session. The Company will not be liable for any loss that
            You may incur as a consequence of unauthorized use of Your Account
            either with or without Your knowledge.
          </li>
          <li>
            3.5. You may be held liable for losses incurred by the Company or
            any other User of or visitor of the Platform due to authorized or
            unauthorized use of Your Account as a result of Your failure in
            keeping Your Account information secure and confidential.
          </li>
          <li>
            3.6. You hereby acknowledge and agree that the deletion of the
            Platform from Your device does not constitute termination of Your
            Account and agree to undertake the process detailed herein in order
            to complete the de-registration of Your Account
            (&ldquo;De-registration&rdquo;). If and when You are desirous of
            having Your name and other details removed from Our records,
            immediately upon receiving Your written request to that effect, We
            shall remove and/delete all such information. However, We may retain
            certain information regarding Your Account, even after receiving a
            deletion request from You, where such retention is required under
            applicable laws or such information is non-personally identifiable
            and aggregated information. You hereby acknowledge that the removal
            of Your details from the Platform does not constitute termination of
            Your outstanding obligations, if any, to the Company.
          </li>
          <li>
            3.7. The information collected while creating Your Account or
            processed for the purposes of availing the Services, will be
            governed by Our Privacy Policy.
          </li>
        </ul>
        <h4>4. Services</h4>
        <p>
          Services provided to You by the Company through the Platform shall
          include the following (<strong>&ldquo;Services&rdquo;</strong>):
        </p>
        <ul>
          <li>
            4.1. A limited, non&ndash;exclusive, non&ndash;transferable, royalty
            free license to use the Platform for the purposes of registering on
            the Platform by creating an Account, and accessing the Software;
          </li>
          <li>
            4.2. Access to digital products/tools in the form of a software as a
            service (&ldquo;Software&rdquo;) that gives You the opportunity to
            create or share content and generate or access links/ sub-domains to
            third party social media platforms through which You can make
            available such content to any third party users on such third party
            platforms (&ldquo;Third Party Platforms&rdquo;); and
          </li>
          <li>
            4.3. Opportunity to enable You to monetize Your services to third
            party users by assisting with facilitation of payments, either
            directly acting as Your collection agent or in association with
            other third party payment aggregators or payment intermediaries. The
            aforementioned services shall be collectively referred to as the
            &ldquo;Services&rdquo;. The Company may, at its discretion, add,
            modify, or remove any of the Services listed above from time to time
            without special notice to You.
          </li>
          <li>
            4.4. All Services on the Platform are provided to You on a principal
            to principal basis between You and the Company. Nothing herein is
            intended to nor be construed to constitute the relationship of a
            principal and agent, employer and employee, partners, joint venture,
            co-owners or otherwise as participants in a joint undertaking or
            representative of the other for any purpose whatsoever.
          </li>
        </ul>
        <h4>5. Updation of Terms and Conditions</h4>
        <ul>
          <li>
            5.1. Your use of the Platform is subject to the Terms, which may be
            updated, amended, modified or revised by Us from time to time
            without notice to You and subject to the terms of the Service
            Agreement. To ensure that You are aware of any additions, revisions,
            amendments or modifications that We may have made to these Terms, it
            is important for You to refer to the Terms from time to time. You
            can determine when this Terms was last modified by referring to the
            &ldquo;Last Updated&rdquo; legend .
          </li>
          <li>
            5.2. The updated Terms shall be effective immediately and shall
            supersede these. It shall be Your responsibility to check this Terms
            periodically for changes. Your continued use of the Services post
            amendment of Terms shall signify Your consent to such amendment, and
            agreement to be legally bound by the same.
          </li>
          <li>
            5.3. Any reference to the Terms shall refer to the latest version of
            these Terms.
          </li>
        </ul>
        <h4>6. Rules and Conduct</h4>
        <ul>
          <li>
            6.1. As a condition of use, You promise not to use the Services for
            any purpose that is prohibited by the Terms; or other rules or
            policies implemented by Us from time to time; or in violation of any
            applicable laws.
          </li>
          <li>
            6.2. By way of example, and not as a limitation, You shall not (and
            shall not permit any third party to) take any action on the Platform
            that: (i) would constitute a violation of any applicable law, rule
            or regulation; (ii) infringes on any intellectual property or other
            right of any other person or entity; (iii) is threatening, abusive,
            harassing, defamatory, libelous, deceptive, fraudulent, invasive of
            another&rsquo;s privacy, tortuous, obscene, offensive, or profane;
            or (iv) impersonates any person or entity. The Company reserves the
            right to disable any Account from the Platform at any time for any
            reason (including, but not limited to, upon receipt of claims or
            allegations from third parties or authorities; or if Company is
            concerned that You may have violated the Terms of Service), or for
            no reason at all with or without notice to the User/Users.
          </li>
          <li>
            6.3. Additionally, You shall not share any information on the
            Platform or through the links to Third Party Platforms created using
            the Software that: (i) may be harmful to minors or children below
            the age of 18 (eighteen) years; (ii) threatens the unity, integrity,
            defense, security or sovereignty of India, friendly relations with
            foreign states or public order or causes incitement to the
            commission of any cognizable offence or prevents investigation of
            any offence or is insulting any other nation; and (iii) is invasive
            of another&rsquo;s privacy, hateful, or racially, ethnically
            objectionable, disparaging, relating or encouraging money laundering
            or gambling, or otherwise unlawful in any manner whatever; (iv)
            harms minors in any manner; (v) infringes any patent, trademark,
            copyright or other proprietary rights; (vi) violates any laws for
            time being; and (vii) impersonate any person.
          </li>
          <li>
            6.4. Furthermore, You shall not (directly or indirectly) on the
            Platform or through the links to Third Party Platforms created using
            the Software: (i) take any action that imposes or may impose an
            unreasonable or disproportionately large load on Company&rsquo;s (or
            its third party providers&rsquo;) infrastructure; (ii) interfere or
            attempt to interfere with the proper working of the Platform or any
            activities conducted on the Platform; (iii) bypass any measures We
            may use to prevent or restrict access to the Platform (or parts
            thereof); (iv) decipher, decompile, disassemble, reverse engineer or
            otherwise attempt to derive any source code or underlying ideas or
            algorithms of any part of the Platform, except to the limited extent
            applicable laws specifically prohibit such restriction; (v) modify,
            translate, or otherwise create derivative works of any part of the
            Platform; or (vi) copy, rent, lease, distribute, or otherwise
            transfer any or all of the rights that You receive hereunder.
          </li>
          <li>
            6.5. You will not access the Platform, and/or its Services, or the
            personal information of other Users, available on the Platform in
            order to build a similar or competitive application, product, or
            service.
          </li>
          <li>
            6.6. You agree to immediately notify Us of any unauthorized use, or
            suspected unauthorized use of Your Profile, or any other breach of
            security, in relation to Your personal information on the Platform.
          </li>
          <li>
            6.7. One Account shall not be used by more than one User. Any use of
            an Account by a third-party would deem to be unauthorized usage. The
            Company reserves the right to disable any such Account from the
            Platform.
          </li>
        </ul>
        <h4>7. Profile Ownership and Editing Rights</h4>
        <ul>
          <li>
            7.1. We ensure easy access to the Users by providing a tool to
            update Your profile information. We reserve the right to moderate
            the changes or updates requested by You and We shall take an
            independent decision whether to publish or reject the requests
            submitted for the respective changes or updates in Your profile.
          </li>
          <li>
            7.2. You hereby represent and warrant that You are fully entitled,
            under applicable law, to provide information as part of Your profile
            or otherwise while using Our Services, and that no such information
            breaches any third-party rights, including intellectual property
            rights and applicable data protection laws. Upon becoming aware of a
            breach of the foregoing representation, We may modify or delete
            parts of Your profile information at Our sole discretion with or
            without notice to You. Excluding Your Account information, You
            acknowledge that the Platform, the entire Company Content ,
            Services, and all the intellectual property rights, including
            copyrights, patents, trademarks, designs, and trade secrets in
            relation to the above are solely owned by Us.
          </li>
        </ul>
        <h4>8. Rights and Obligation relating to the usage of the Platform</h4>
        <ul>
          <li>
            8.1. Users shall be prohibited from carrying out the any illegal
            acts in the Platform or through the links to Third Party Platforms
            created using the Software including but not limited to acts
            mentioned below:
            <br />a ) violating or attempting to violate the integrity or
            security of the Platform;
            <br />b ) transmitting any information on or through the Platform
            that is disruptive or competitive to the provision of Our Services;
            <br />c ) intentionally submitting on the Platform any incomplete,
            false or inaccurate information;
            <br />d ) using any engine, software, tool, agent or other device or
            mechanism (such as spiders, robots, avatars or intelligent agents)
            to navigate or search the Platform or any Third Party Platform;
            <br />e ) circumventing or disabling any digital rights management,
            usage rules, or other security features of the Platform. Any
            unlawful activities in the Platform which are prohibited by laws of
            India
          </li>
          <li>
            8.2. The Company shall, upon obtaining knowledge by itself or been
            brought to actual knowledge by an affected person in writing or
            through email signed with electronic signature Your violation of
            these Terms, be entitled to disable Your Access to the Account and
            use of Services. We shall also be entitled to preserve such
            information and associated records for at least 90 (ninety) days or
            such shorter time as prescribed by law, for production to
            governmental authorities for investigation purposes. In case of
            non-compliance with these Terms, any applicable laws, rules or
            regulations, the Service Agreement or the Privacy Policy by a User,
            We shall have the right to immediately terminate Your access or
            usage rights to the Platform and Services and to remove
            non-compliant information from the Platform.
          </li>
          <li>
            8.3. We may disclose or transfer User-generated information to Our
            affiliates or governmental authorities in such manner as permitted
            or required by applicable law, and You hereby consent to such
            transfer. In accordance with the applicable laws, We shall transfer
            sensitive personal data or information including any information, to
            any other body corporate or a person in India, or located in any
            other country, that ensures the same level of data protection that
            is adhered to by Us, only if such transfer is necessary for the
            performance of the lawful contract between Company or any person on
            its behalf and the User or where the User has consented to data
            transfer.
          </li>
        </ul>
        <h4>9. Third Party Services</h4>
        <ul>
          <li>
            9.1. While availing Services, Users may connect with third-party
            service providers. The Company is not responsible for, and does not
            endorse, any third-party services mentioned on the Platform. It is
            hereby stated that Company shall in no way be responsible for any
            acts or omissions of third parties. Any transaction, dealings or
            communication otherwise that the User may have with such third
            parties are at the User&rsquo;s own risk and We make no warranties,
            express or implied regarding the quality or suitability of the
            services or products of such third-party vendors.
          </li>
        </ul>
        <h4>10. Confidentiality</h4>
        <ul>
          <li>
            10.1. The Parties may disclose to each other and their designated
            agents and/or advisors Confidential Information as may be required
            for the performance of the Services and execution of a Campaign.
          </li>
          <li>
            10.2. Each party undertakes that it will keep secret and
            confidential the terms of the Service Agreement and any Confidential
            Information supplied by either party in connection with the Service
            Agreement or in connection with the business of the other and in
            connection with the Services and Campaign and shall only disclose
            such information or part thereof (except to its own employees and
            advisers and then only on a need to know basis) with the other
            party&rsquo;s prior written consent <strong>PROVIDED THAT</strong>{" "}
            this clause shall not extend to information which was and can be
            shown to be rightfully in the possession of the receiving party
            prior to the commencement of the negotiations leading to the Service
            Agreement or which is in the public domain (other than as a result
            of a breach of this clause).
          </li>
        </ul>
        <h4>
          11. Use of Your information and content displayed on the Platform or
          Third Party Platforms
        </h4>
        <ul>
          <li>
            11.1. We will only use the information You provide as permitted by
            Our Privacy Policy and applicable law. Please closely review Our
            Privacy Policy for more information regarding how We use and
            disclose Your personal information. Our Privacy Policy is hereby
            incorporated into these Terms of Service by this reference.
          </li>
          <li>
            11.2. We reserve the right to maintain, delete or destroy all
            information and materials posted or uploaded through the Services,
            pursuant to Our internal record retention and/or destruction
            policies. We (may/may not) make use of third-party cloud services
            providers or use Our own service infrastructure for hosting the
            servers and databases. While We make commercially reasonable efforts
            to ensure that the data stored on Our servers is persistent and
            always available to the User, We will not be responsible in the
            event of failure of the third-party servers or any other factors
            outside Our reasonable control that may cause the User&rsquo;s data
            to be permanently deleted, irretrievable, or temporarily
            inaccessible.
          </li>
          <li>
            11.3. You acknowledge and agree that We may preserve Your
            information and may also disclose Your related information if
            required to do so by law; or in the good faith belief that such
            preservation or disclosure is reasonably necessary to: (a) comply
            with legal process, applicable laws or government requests; (b)
            enforce these Terms; (c) respond to claims that any of Your usage of
            the Platform violates the rights of third parties; (d) detect,
            prevent, or otherwise address fraud, security or technical issues;
            or (e) protect the rights, property, or personal safety of the
            Platform, its users, or the public.
          </li>
          <li>
            11.4. We reserve the right to remove or disable access to any user
            information hosted on Our Platform.
          </li>
        </ul>
        <h4>12. Intellectual Property Rights</h4>
        <ul>
          <li>
            12.1. The Platform and the processes, and their selection and
            arrangement, including but not limited to, all text, videos,
            graphics, user interfaces, visual interfaces, sounds and music (if
            any), artwork and computer code (and any combinations thereof)
            (collectively, the <strong>&ldquo;Company Content&rdquo;</strong>)
            on the Platform is owned by the Company and the design, structure,
            selection, coordination, expression, look and feel and arrangement
            of such Company Content is protected by copyright, patent and
            trademark laws, and various other intellectual property rights.
          </li>
          <li>
            12.2. The trademarks, logos and service marks displayed on the
            Platform (&ldquo;Marks&rdquo;) are the property of the Company or
            other respective third parties, as the case may be. You are not
            permitted to reproduce or distribute or otherwise use the Marks
            without the prior consent of the Company or the third party that may
            own the Marks.
          </li>
        </ul>
        <h4>13. Limitation of Liability</h4>
        <ul>
          <li>
            13.1. TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
            COMPANY (INCLUDING ITS DIRECTORS, EMPLOYEES, AGENTS, SPONSORS,
            PARTNERS, SUPPLIERS, CONTENT PROVIDERS, LICENSORS OR RESELLERS,) BE
            LIABLE UNDER CONTRACT, TORT, STRICT LIABILITY, NEGLIGENCE OR ANY
            OTHER LEGAL OR EQUITABLE THEORY WITH RESPECT TO THE SERVICES (I) FOR
            ANY LOST PROFITS, DATA LOSS, LOSS OF GOODWILL OR OPPORTUNITY, OR
            SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF
            ANY KIND WHATSOEVER, (II) FOR YOUR RELIANCE ON THE SERVICES (III)
            FOR ANY DAMAGES (IV) FOR ANY MATTER BEYOND ITS OR THEIR REASONABLE
            CONTROL, EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF ANY
            OF THE AFOREMENTIONED DAMAGES (V) FOR ANY THIRD PARTY CLAIMS IN
            RELATION TO YOUR USE OF THE SOFTWARE OR CONTENT/INFORMATION SHARED
            BY YOU THROUGH/WITH THE HELP OF THE SOFTWARE.
          </li>
        </ul>
        <h4>14. Disclaimer</h4>
        <ul>
          <li>
            14.1. THE SERVICE AND PLATFORM IS PROVIDED &ldquo;AS IS&rdquo; AND
            &ldquo;AS AVAILABLE&rdquo; AND IS WITHOUT WARRANTY OF ANY KIND,
            EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
            WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS
            FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES IMPLIED BY ANY COURSE
            OF PERFORMANCE OR USAGE OF TRADE, ALL OF WHICH ARE EXPRESSLY
            DISCLAIMED. THE COMPANY AND ITS DIRECTORS, EMPLOYEES, AGENTS,
            SUPPLIERS, SHAREHOLDERS AND PARTNERS DO NOT WARRANT THAT: (A) THE
            SERVICE WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR
            LOCATION; (B) THE QUALITY OF ANY SERVICES, AVAILED BY YOU THROUGH
            THE SERVICE WILL MEET YOUR EXPECTATIONS; (C) ANY DEFECTS OR ERRORS
            WILL BE CORRECTED; (D) ANY CONTENT OR SOFTWARE AVAILABLE AT OR
            THROUGH THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS;
            OR (E) THE RESULTS OF USING THE SERVICE WILL MEET YOUR REQUIREMENTS
            OR THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE. YOUR USE OF
            THE SERVICE IS SOLELY AT YOUR OWN RISK.
          </li>
          <li>
            WE DON&rsquo;T PROMISE TO STORE OR KEEP SHOWING ANY INFORMATION AND
            CONTENT THAT YOU&rsquo;VE POSTED. CREATORAPP IS NOT A STORAGE
            SERVICE. YOU AGREE THAT WE HAVE NO OBLIGATION TO STORE, MAINTAIN OR
            PROVIDE YOU A COPY OF ANY CONTENT OR INFORMATION THAT YOU OR OTHERS
            PROVIDE, EXCEPT TO THE EXTENT REQUIRED BY APPLICABLE LAW AND AS
            NOTED IN OUR PRIVACY POLICY.
          </li>
          <li>
            THE COST OF PROCUREMENT OF THE SERVICES RESULTING FROM ANY DATA,
            CONTENT OR INFORMATION PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR
            NOT OBTAINED OR RECEIVED FROM ANY PAID GROUP/CHANNEL OR ANY OTHER
            USER IS SOLELY AND ENTIRELY AT YOUR OWN RISK. YOU HEREBY
            ACKNOWELEDGE AND AGREE THAT WE PROVIDE NO GUARANTEE OR SURETY OF
            ENGAGEMENT BETWEEN YOU AND YOUR VIEWERS UPON PAYMENT AND TAKE NO
            RESPONSIBILITY OF ENSURING FULL SCALE INTERACTION BETWEEN YOU AND
            YOUR VIEWERS.
          </li>
          <li>
            YOU HEREBY ACKNOWLEDGE AND AGREE THAT YOU WILL SHALL ONLY PROVIDE
            TRUE AND CORRECT INFORMATION AND IN THE CASE OF CREATING A PROFILE
            YOU UNDERTAKE TO AT ALL TIMES KEEP THE INFORMATION UP TO DATE. UNDER
            NO CIRCUMSTANCES THE COMPANY WILL BE LIABLE ON ACCOUNT OF ANY
            INACCURACY OF INFORMATION PROVIDED BY YOU ON THIS PLATFORM. IT IS
            THE RESPONSIBILITY OF THE USER TO FURTHER RESEARCH THE INFORMATION
            ON THE SITE
          </li>
          <li>
            YOU HEREBY ACKNOWLEDGE AND AGREE THAT THE COMPANY SHALL NOT BE
            LIABLE FOR ANY CONTENT OR MATERIALS PUBLISHED BY YOU THROUGH THE
            SERVICES. IT IS HEREBY CLARIFIED THAT YOU SHALL BE LIABLE FOR
            CONTENT OR MATERIALS PUBLISHED BY YOU THROUGH THE SERVICES AND THAT
            THE COMPANY SHALL BE UNDER NO OBLIGATION IN RELATION TO SUCH CONTENT
            AND MATERIALS. FURTHER YOU AGREE AND ACKNOWLEDGE THAT THROUGH YOUR
            USE OF THE SERVICES, YOU SHALL NOT UNDERTAKE ANY ACTIVITY WHICH IS
            UNLAWFUL IN NATURE. ANY LIABILITY ARISING OUT OF SUCH UNLAWFUL
            ACTIVITY SHALL SOLELY REST WITH YOU AND THE COMPANY SHALL NOT HAVE
            ANY LIABILITY IN RELATION TO THE SAME. YOU SHALL BE RESPONSIBLE FOR
            COMPLYING WITH APPLICABLE LAWS, RULES, REGULATIONS AND THESE TERMS.
          </li>
        </ul>
        <h4>15. Indemnification</h4>
        <ul>
          <li>
            15.1. You shall defend, indemnify, and hold harmless the Company,
            its affiliates/subsidiaries/joint venture partners and each of its,
            and its affiliates&rsquo;/subsidiaries/joint venture partners&rsquo;
            employees, contractors, directors, suppliers and representatives
            from all liabilities, losses, claims, and expenses, including
            reasonable attorneys&rsquo; fees, that arise from or relate to (i)
            Your use or misuse of, or access to, the Services, Software and
            Platform; or (ii) Your violation of the Terms and Conditions; or any
            applicable law, contract, policy, regulation or other obligation
            including that of the Third Party Platforms. We reserve the right to
            assume the exclusive defense and control of any matter otherwise
            subject to indemnification by You, in which event You will assist
            and cooperate with Us in connection therewith.
          </li>
        </ul>
        <h4>16. Fees/Payments</h4>
        <p>
          You agree and acknowledge that You shall be charged such amount
          towards subscription of Services as set out in the Service Agreement
          executed with the Company.
        </p>
        <h4>17. Violation of the Terms</h4>
        <ul>
          <li>
            17.1. You agree that any violation by You of these Terms will
            constitute an unlawful and unfair business practice, and will cause
            irreparable harm to the Company, for which monetary damages would be
            inadequate, and You consent to the Company obtaining any injunctive
            or equitable relief that they deem necessary or appropriate in such
            circumstances. These remedies are in addition to any other remedies
            that the Company may have at law or in equity.
          </li>
        </ul>
        <h4>18. Suspension and Termination</h4>
        <ul>
          <li>
            18.1. The Terms will continue to apply until terminated by either
            You or the Company as set forth below. If You object to the Terms or
            are dissatisfied with the Platform, Your only recourse is to (i)
            close Your Account on the Platform; and/or (ii) stop accessing the
            Platform.
          </li>
          <li>
            18.2. We may temporarily suspend access to the whole or any part of
            the Services for pre-scheduled maintenance. The intent to
            temporarily suspend access for pre-scheduled maintenance shall be
            communicated to You 48 hours in advance via email to the email id
            provided by You upon creation of Your Account. If You choose to
            access the Platform or avail Services during such pre-scheduled
            maintenance, We cannot guarantee the availability of the Services
            and/or functionality of the Platform.
          </li>
          <li>
            18.3. The Company may delist You or block Your future access to the
            Platform or suspend or terminate Your Account if it believes, in its
            sole and absolute discretion that You have infringed, breached,
            violated, abused, or unethically manipulated or exploited any term
            of these Terms or the Privacy Policy or anyway otherwise acted
            unethically. Notwithstanding anything in this clause, these Terms
            will survive indefinitely unless and until the Company chooses to
            terminate them.
          </li>
          <li>
            18.4. If You or the Company terminate Your use of the Platform, the
            Company may delete any Company Content or other materials relating
            to You and the Company shall have no liability to You or any third
            party for doing so. However, Your transactions details may be
            preserved by the Company for purposes of tax or regulatory
            compliance.
          </li>
          <li>
            18.5. We may terminate Your usage of the Platform at any time for
            any reason, including breach of the Terms. We have the right (but
            not the obligation) to refuse to grant access to Platform. Except
            for the rights and license granted in these terms, We reserve all
            other rights and grant no other rights or licenses, implied or
            otherwise.
          </li>
          <li>
            18.6. Once temporarily suspended, indefinitely suspended or
            terminated, the User may not continue to use the Platform under the
            same account, a different account or re-register under a new
            account. On termination of an account due to the reasons mentioned
            herein, such User shall no longer have access to data, messages and
            other material kept on the Platform by such User. All provisions of
            the Terms, which by their nature should survive termination, shall
            survive termination, including, without limitation, warranty
            disclaimers, indemnity and limitations of liability.
          </li>
          <li>
            18.7. You shall be liable to pay any fees or charges as may be
            applicable in respect of the Services until the date of termination
            by either party whatsoever.
          </li>
        </ul>
        <h4>19. Exemptions to liability of Company</h4>
        <ul>
          <li>
            19.1. You further agree and confirm that Company shall not be
            responsible, in any manner whatsoever, for any delay/unavailability
            of Services or failure to meet its obligations under the Terms and
            Conditions, which may be caused, directly or indirectly, due to:
            <br />a ) Your failure to cooperate;
            <br />b ) Your unavailability and/or unresponsiveness;
            <br />c ) Your failure to provide accurate and complete information;
            <br />d ) any event beyond Company&rsquo;s reasonable control.
          </li>
        </ul>
        <h4>20. Governing Law and Jurisdiction</h4>
        <ul>
          <li>
            20.1. These Terms shall be governed by and construed in accordance
            with the laws of India without regard to the conflict of law
            provisions thereof. All claims, differences and disputes arising
            under or in connection with or in relation hereto the Platform or
            Services, the Terms or any transactions entered into on or through
            the Platform or Services shall be subject to the exclusive
            jurisdiction of the courts at Bangalore, Karnataka, India and You
            hereby accede to and accept the jurisdiction of such courts.
          </li>
        </ul>
        <h4>21. General Provisions</h4>
        <ul>
          <li>
            21.1. Notice: All notices under the Terms and Conditions will be in
            writing and will be deemed to have been duly given when received, if
            personally delivered or sent by certified or registered mail, return
            receipt requested; when receipt is electronically confirmed, if
            transmitted by facsimile or e-mail; or two days after it is sent, if
            sent for next day delivery by recognized overnight delivery service.
          </li>
          <li>
            21.2. Assignment: You cannot assign or otherwise transfer the Terms,
            or any rights granted hereunder to any third party. The
            Company&rsquo;s rights under the Terms are freely transferable by
            the Company to any third party without the requirement of seeking
            Your consent.
          </li>
          <li>
            21.3. Relationship: No agency, partnership, joint venture, or
            employment relationship is created as a result of the Terms and
            Conditions and neither party has any authority of any kind to bind
            the other in any respect.
          </li>
          <li>
            21.4. Severability: If, for any reason, a court of competent
            jurisdiction finds any provision of the Terms, or any portion
            thereof, to be unenforceable, that provision shall be enforced to
            the maximum extent permissible so as to give effect to the intent of
            the parties as reflected by that provision, and the remainder of the
            Terms shall continue in full force and effect.
          </li>
          <li>
            21.5. Waiver: Any failure by Company to enforce or exercise any
            provision of the Terms, or any related right, shall not constitute a
            waiver by Company of that provision or right.
          </li>
        </ul>
        <h4>22. Alerts Provided by The Company</h4>
        <ul>
          <li>
            22.1. The Company provides You with multiple automatic alerts while
            providing Services.
          </li>
          <li>
            22.2. You understand and agree that any alerts provided to You
            through the Platform may be delayed or prevented by a variety of
            factors. We will do Our best to provide alerts in a timely manner
            with accurate information. However, We neither guarantee the
            delivery nor the accuracy of the content of any alert. You also
            agree that We shall not be liable for any delays, failure to
            deliver, or misdirected delivery of any alert; for any errors in the
            content of an alert; or for any actions taken or not taken by You or
            any third party in reliance on an alert.
          </li>
        </ul>
        <h4>23. Contact You</h4>
        <ul>
          <li>
            23.1. You agree that We may contact You through telephone, email,
            SMS, or any other means of communication for the purpose of:
            <br />a ) Obtaining feedback in relation to Platform or Our
            Services;
            <br />b ) Resolving any complaints, information, or queries; and
            <br />c ) You agree to provide Your fullest co-operation further to
            such communication by Company.
          </li>
          <li>
            23.2. By submitting suggestions or other feedback regarding Our
            Services/Platform, You agree that We can use and share such feedback
            for any purpose without any compensation to You and We are under no
            obligation to keep such feedback confidential.
          </li>
        </ul>
        <h4>24. Grievance Redressal Mechanism</h4>
        <ul>
          <li>
            24.1. Any discrepancies or grievances with regard to content and or
            comment or breach of the Terms and Conditions shall be taken up with
            the designated Grievance Officer as mentioned below via in writing
            or through email signed with the electronic signature to
            <br />
            <br />
            <strong>Email:</strong> greviance@creatorapp.in
            <br />
            <strong>Address:</strong>
            <strong>
              459 1st floor khata no 357/459 HSR Layout, Bangalore South,
              Bangalore, Karnataka
            </strong>
            , India.
          </li>
          <li>
            24.2. In furtherance of the Consumer Protection Act 2019 and the
            Consumer Protection (E-Commerce) rules 2020 nodal officer appointed
            to ensure compliance (to the extent relevant and applicable on the
            Company) with the Act and E-commerce Rules is as follows:
            <br />
            <br />
            <strong>Contact Details:</strong> greviance@creatorapp.in
            <br />
            <br />
          </li>
          <li>
            24.3. The grievance officer will acknowledge the receipt of any
            compliant within 24 hours and redress the complaint within 15 days
            from receipt of the complaint.
          </li>
        </ul>
        <h4>25. Company and User Materials</h4>
        <ul>
          <li>
            25.1. While rendering Services, Company directly or through its
            representatives, may provide Users with certain materials relevant
            to the Services, which may be in the form of audio, video, written
            and oral content (<strong>&ldquo;Company Materials&rdquo;</strong>).
            Company Materials shall be the exclusive property of the Company.
            User hereby agrees and acknowledges that he/she shall ensure that
            the Company Materials are not shared with any third party, without
            Company&rsquo;s written consent and any breach of such nature shall
            cause financial and irreparable injury to Company. Company hereby
            provides User with a revocable, non-exclusive, non-transferable,
            non-sublicensable, limited license to use the Company Materials
            solely for its personal purpose and not for any commercial use.
            While availing Services, User may submit various materials to
            Company in the form of audio/video/image/written content, (
            <strong>&ldquo;User Materials&rdquo;</strong>). User hereby provides
            Company with an exclusive, transferrable, perpetual and irrevocable
            license to use the User Materials for its use. User hereby agrees
            and acknowledges that User Materials shall not infringe any
            intellectual property rights of third party and shall be responsible
            for any claims arising out of infringement.
          </li>
        </ul>
        <h4>26. Modification</h4>
        <ul>
          <li>
            26.1. We reserve the right, at any time and in with sole discretion,
            to change, modify, or amend the Platform (in whole, or in part) or
            any of its Services or Company Content (in whole, or in part), in
            compliance with the applicable legal and regulatory framework. You
            agree that We will not be liable to You for any change, modification
            or amendment of the Platform or its Services, or any part thereof.
          </li>
        </ul>
        <h4>27. Support</h4>
        <ul>
          <li>
            27.1. The Company offers a chat-based support system along with an
            online knowledge pool of FAQs. In case You require any assistance or
            support, You may access support resources or contact Our support by
            emailing at support@creatorapp.in and raise a ticket for Your query.
          </li>
          <li>
            27.2. The Company shall revert to every complaint within 24 hours of
            receipt of the complaint. Further, the Company shall take best
            possible efforts to redress the complaint within 15 days of receipt
            of the complaint. Any suggestions by Company regarding use of the
            Services shall not be construed as a warranty.
          </li>
          <li>
            27.3. The User agrees and acknowledges that the Company shall
            address and attempt to resolve the complaint received in accordance
            with the standard policies and procedures adopted by the Company,
            the User&rsquo;s disapproval/discontent with the outcome/mode of
            redressal shall not be deemed to mean non-redressal of the complaint
            by the Company. Any suggestions by Company regarding use of the
            Service shall not be construed as a warranty.
          </li>
        </ul>
        <h4>28. Contact</h4>
        <ul>
          <li>
            28.1. If You have any questions regarding the Services or usage of
            the Platform, please contact Company at support@creatorapp.in.
            Please note that for the purpose of validation, You shall be
            required to provide information (including, but not limited to
            contact number or registered mobile number, etc.) for the purpose of
            validation and taking Your service request.
          </li>
        </ul>
        <p>
          <strong>Copyright &copy; All rights reserved.</strong>
        </p>
        <p>Last Updated : March 2024</p>
      </div>
    </div>
  );
};

export default Terms;
