export const IMAGES = {
  LOGO: "/images/branding/logo.png",
  STAR_LOGO: "/images/branding/star.png",
  LANDINGIMAGE: "/images/landingPage/landingImage.png",
  REVENUEIMAGE: "/images/landingPage/revenueImage.png",
  COMMUNITYIMAGE: "/images/landingPage/communityImage.png",
  CATEGORIESIMAGE: "/images/categories/categories.png",
  LOGINIMAGE: "/images/login/login.png",
  SIGNUPIMAGE: "/images/signup/signup.png",
  PROFILECOVERIMAGE: "images/profile/profileFrame.png",
  NOIMAGE: "images/profile/noImages.png",
  PROFILEIMAGE: "images/profile/profileImage.png",
  NODOCUMENT: "images/profile/NoDocuments.png",
  VIDEOIMAGE: "images/postImages/videoImage.png",
  POSTIMAGE: "images/postImages/postImage.png",
  USERIMAGE: "images/userImages/profileImage.png",
  UPLOADPOSTIMAGE: "images/postImages/uploadPostImage.png",
  UPLOADIMAGE: "images/postImages/uploadImage.png",
  LIVESTREAMIMAGE: "images/postImages/liveStreamImage.png",
  EDITPROFILECOVERIMAGE: "images/profile/editProfileCoverImage.png",
  EDITPROFILEIMAGE: "images/profile/editProfilemage.png",
  textVioletTHEMEIMAGE: "images/themeImages/violetThemeImage.png",
};
